project:
  type: website

website:
  site-url: https://datadisco.cdss.berkeley.edu
  #site-url: https://berkeley-cdss.github.io/datadisco
  title: "Data Discovery"
  sidebar:
    style: docked
    logo: assets/CDSS_LOGO_NEW_FOOTER.svg
    contents:
      #- href: index.qmd
      - href: index.qmd
      - href: ddmatch.qmd
      - href: get-involved/partner.qmd
        contents:
          - href: ddmatch/create-partner.qmd
          - href: ddmatch/create-project.qmd
          - href: ddmatch/extend-offer.qmd
          - href: ddmatch/list-offer.qmd
      - href: get-involved/student-researchers.qmd
        contents:
          - href: ddmatch/create-student.qmd
          - href: ddmatch/review-offer.qmd
      - href: program-team.qmd

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true
    include-in-header:
      file: siteimprove.html
