---
title: "For Student Researchers"
---

## Overview
As a Data Discovery student researcher, you'll work on a team with a project mentor, using data to understand real-world problems. Through the associated Data Discovery course, you'll earn course credit for your work on the project and develop professional skills to support your progress.

## Timeline
Exact program deadlines vary by semester. Typically, Data Discovery applications open to students about 2 weeks before instruction begins. For the most competitive application, apply by the priority deadline, about 1 week before classes start. The application closes during the first week of class. Most project mentors will schedule an interview before making an offer. You can add yourself to the Data Discovery course waitlist once you've scheduled an interview. If you accept an offer, you'll be moved from the waitlist and admitted to the course. Work on the project will end during the last week of class, with a final presentation during RRR week.

### Fall 2025 Deadlines
- **DDMatch student application portal opens:** August 11. Begin reading the project descriptions and preparing your application(s).
- **Priority deadline:** August 18. Get your application in by the priority deadline (11:59pm) to have the most competitive application. Partners may form teams before the extended deadline closes.
- **Extended deadline:** August 27. Take advantage of the extended deadline if you can’t make the priority deadline or want to apply to additional projects.
- **Team formation:** September 3. Decisions are expected by September 3.
- **First day of class:** September 8. The first Data Discovery course meeting will be Monday, September 8, 3-5 pm. All participants should plan to attend.

## Requirements
- **Who can participate:** Any UC Berkeley undergraduate and masters students enrolled in any in-person program.
- **One project:** Students may participate in one Data Discovery project per semester, even if they are selected for more than one.
- **Teamwork:** Students work in teams, including developing expectations for the team with the mentor.
- **Course enrollment:** Students will enroll in the Data Discovery course for 3 or 4 units. The course includes a dedicated team meeting time alongside guest lectures and group discussions to build professional skills.
- **Final project:** A poster summarizing the research to be presented at the Data Discovery Symposium during RRR week.

## Application
- **Max applications:** You may apply for up to 10 projects (you may participate in only one).
- **Questions:** Submit the form responding to these questions for each project you want to apply to, using the link in the project description. Refer to the specific instructions in the description for each project, and address all relevant details for a complete application. See the guide for the list of questions in the application.
"""