name: build-deploy

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Jupyter and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbformat

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Render and Publish
        run: quarto publish gh-pages --no-prompt
